# Your Name or Company
title: El jardín de las ánimas

# Description of your website. This is used for social sharing.
description:  Página oficial del nuevo libro del autor Juan Cañavate

# A brief blurb about yourself
content: El jardín de las ánimas es una obra de ficción que trata de uno de los capítulos más tristes de la historia de España, el Desastre de Annual en el año 1921. El jardín de las ánimas es también y, sobre todo, un libro dedicado, con respeto y emoción, a la memoria de los que allí murieron y también a los que sobrevivieron y tuvieron que seguir viviendo con el dolor de haber sido testigos de tanto sufrimiento.
# Add your social links
social:
  - platform: El autor
    url: https://jncvt.github.io/autor.html
  - platform: Encargar la novela
    url: https://jncvt.github.io/encargar.html
autor: Melillense de adopción, ciudad en la que vivió su infancia y adolescencia, el autor de ´´El jardín de las ánimas´´ se trasladó al inicio de sus estudios universitarios a Granada, localidad donde en la actualidad vive. Es licenciado en Geografía e Historia por la UGR donde, además, realizó su doctorado en Historia Medieval y donde, en la actualidad,es profesor colaborador del Máster de Arqueología de la UGR. Su carrera profesional la ha desarrollado como Arqueólogo en la Junta de Andalucía en las provincias de Almería, Sevilla y Granada. Es autor de diferentes libros y publicaciones de carácter académico, especialmente dedicados a la transición urbanística de la Granada nazarí a la Granada castellana. En la actualidad ha trabajado y lo sigue haciendo en distintas investigaciones y publicaciones dedicadas al fenómeno del morabitismo en la Granada Medieval.
informacion: La manera más sencilla de conseguir la novela es a través del correo eletrónico. Envía un correo al autor a través de la dirección jncvt2008@gmail.com .


# General settings
# url: http://brianmaierjr.github.com/uni
# baseurl: "/uni" 
markdown: kramdown
sharing_image: share.jpg
# google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
